version: "3.7"
services:
  app:
    build:
      args:
        user: ta
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: some
    container_name: some-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - some
  # db:
  #   image: mysql:5.7
  #   container_name: some-db
  #   command: --disable-partition-engine-check
  #   ports:
  #     - "8001:3306"
  #   environment:
  #     restart: unless-stopped
  #     MYSQL_DATABASE: some
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_PASSWORD: password
  #     MYSQL_USER: user
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - dbdata:/var/lib/mysql/
  #     - ./docker-compose/mysql:/docker-entrypoint-initdb.d
  #   networks:
  #     - some
  nginx:
    image: nginx:1.17-alpine
    container_name: some-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - some
networks:
  some:
    driver: bridge
volumes:
  dbdata:
    driver: local

    