version: "3.7"
services:
  app:
    build:
      args:
        user: ta
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: some
    container_name: some-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/app/php.ini:/usr/local/etc/php/php.ini
    networks:
      - some
  db:
    image: mysql:8.0.33
    container_name: some-mysql
    restart: unless-stopped
    environment:
         MYSQL_DATABASE: ${DB_DATABASE}
         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
         MYSQL_PASSWORD: ${DB_PASSWORD}
         MYSQL_USER: ${DB_USERNAME}
         SERVICE_TAGS: dev
         SERVICE_NAME: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
     - some
  nginx:
    image: nginx:1.17-alpine
    container_name: some-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - some
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - 8002:80
#    environment:
#      - PMA_HOST=127.0.0.1
#      - PMA_USER=root
#      - PMA_PASSWORD=root
#    networks:
#      - some
networks:
  some:
    driver: bridge
volumes:
  data:
    driver: local
