version: "3.7"
services:
  app:
    build:
      args:
        user: ta
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: some
    container_name: some-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - some
  db:
    image: mysql:8.0.33
    container_name: some-mysql
    restart: unless-stopped
    environment:
         MYSQL_DATABASE: some
         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
         MYSQL_PASSWORD: password
         MYSQL_USER: user
         SERVICE_TAGS: dev
         SERVICE_NAME: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
     - some
  nginx:
    image: nginx:1.17-alpine
    container_name: some-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - some
networks:
  some:
    driver: bridge
volumes:
  data:
    driver: local
