#!/bin/bash

if [[("$1" == "enter") && ("$2" == "root")]]; then
    container_name=$3
    docker exec -it -u root "$container_name" bash
    exit
fi

if [ "$1" == "enter" ]; then
    container_name=$2
    if [[ "$2" =~ "mysql" ]]; then
        docker exec -it "$container_name" bash  -c "mysql -h 127.0.0.1 -u ta -p"
    else
        docker exec -it "$container_name" bash
    fi
else
    case $1 in
        "start")
            docker-compose up -d
            ;;
        "stop")
            docker-compose down
            ;;
        "restart")
            docker-compose restart
            ;;
        "logs")
            docker-compose logs -f
            ;;
        "ps")
            docker ps | grep $2
            ;;
        "rebuild")
            containers = docker ps | grep $2 | awk '{print $1}'
            docker-compose down && docker rm "$containers"
            docker-compose up -d
            ;;
        *)
            echo "Invalid command. Usage: please [start|stop|restart|enter|logs|ps|enter-root] [container_name]"
            ;;
    esac
fi
